### ISSUE TITLE
Make embedding images in README.md compatible to GitLab and GitHub

### ISSUE THREAD

**Issue by dersimn** [scm-manager/scm-readme-plugin#41]
## Issue description

Markdown README files in SCM Manager not displaying images:

Files in repository:
```
- README.md
- placeholder.png
```

Content of `README.md`:

```
1
![](placeholder.png)

3
![](content/master/placeholder.png)

4
![](../content/master/placeholder.png)

5
![](content/bd99365c469ef3db8f1336a4db331d3d342cb1ed/placeholder.png)

6
![](../content/bd99365c469ef3db8f1336a4db331d3d342cb1ed/placeholder.png)

7
![](https://example.com/scm/api/v2/repositories/test/readme-image-files/content/master/placeholder.png)

8
![](https://example.com/scm/api/v2/repositories/test/readme-image-files/content/<FULL SHA>/placeholder.png)
```

Only variant 7 und 8 (with hard-coded URL) are working in SCM Manager. This however makes `README.md` specific to one instance of SCM Manager and moreover incompatible to GitLab and GitHub where variant 1 is used.

#### Problem to be solved

Images not being displayed unless full hard-coded URL is used.

#### Proposed solution

Solve URLs in `README.md` relative to their location within the repository, see [GitLab Docs](https://docs.gitlab.com/ee/user/markdown.html#images) and [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images)

**Comment by pfeuffer** [comment]
Thanks for the feedback, @dersimn . You are definitely right and we have this on our to-do list.

We will track this with issue scm-manager/scm-manager#1979, so I will close this ticket as a duplicate.
